PLAYERDATA_CLIENT_ID="yGhhyBnkZu_VA0Y5Qj0D-snMUQsHwXuq6NCt5S1TTWA"
PLAYERDATA_CLIENT_SECRET="LFKNJ3ud-vdlhJbCTv1xnJwng-SacBz_WTicW1AYadc"
PLAYERDATA_TOKEN_URL="https://app.playerdata.co.uk/oauth/token"
PLAYERDATA_GRAPHQL_URL="https://app.playerdata.co.uk/api/graphql"

[COACH_ACCESS]
# Map coach emails to the team names they can access. Multiple teams allowed.
# Use the PlayerData/Bolts naming; the app will map to Excel team keys by year.
# Example configuration for Boston Bolts coaches:
"kyleryan@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2013"]
"denispetro@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2012"]
"bryce@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2011"]
"seannapier@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2010"]
"jonnyburns@bostonbolts.com" = [
  "Boston Bolts MLS Next Homegrown 2009",
  "Boston Bolts MLS Next Homegrown 2007/2008"
]
