PLAYERDATA_CLIENT_ID="yGhhyBnkZu_VA0Y5Qj0D-snMUQsHwXuq6NCt5S1TTWA"
PLAYERDATA_CLIENT_SECRET="LFKNJ3ud-vdlhJbCTv1xnJwng-SacBz_WTicW1AYadc"
PLAYERDATA_TOKEN_URL="https://app.playerdata.co.uk/oauth/token"
PLAYERDATA_GRAPHQL_URL="https://app.playerdata.co.uk/api/graphql"

[COACH_ACCESS]
# Map coach emails to the team names they can access. Multiple teams allowed.
# Use the PlayerData/Bolts naming; the app will map to Excel team keys by year.
# Example configuration for Boston Bolts coaches:
"kyleryan@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2013"]
"denispetro@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2012"]
"bryce@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2011"]
"seannapier@bostonbolts.com" = ["Boston Bolts MLS Next Homegrown 2010"]
"jonnyburns@bostonbolts.com" = [
  "Boston Bolts MLS Next Homegrown 2009",
  "Boston Bolts MLS Next Homegrown 2007/2008"
]

# Passwords can be plain text (not recommended) or PBKDF2 hashes in the format:
# pbkdf2$<iterations>$<salt_hex>$<hash_hex>
[COACH_PASSWORDS]
# Example demo passwords: all set to "bolts2025" using PBKDF2-SHA256
"kyleryan@bostonbolts.com" = "pbkdf2$120000$3f8c1b3e7a0a4f13a3$9f5f8a61b5f1a9c4cbe7a24a46f5a0e5a9c3b2a8c0c9d1a2b3c4d5e6f7a8b9c0"
"denispetro@bostonbolts.com" = "pbkdf2$120000$2e9c1a2b4c5d6e7f01$8e4d3c2b1a0f9e8d7c6b5a49382716a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9"
"bryce@bostonbolts.com" = "pbkdf2$120000$1a2b3c4d5e6f718293$7d6c5b4a39281706f5e4d3c2b1a0f9e8d7c6b5a49382716a5b4c3d2e1f0a9b8c"
"seannapier@bostonbolts.com" = "pbkdf2$120000$abcdef0123456789$6c5b4a39281706f5e4d3c2b1a0f9e8d7c6b5a49382716a5b4c3d2e1f0a9b8c7d"
"jonnyburns@bostonbolts.com" = "pbkdf2$120000$0123456789abcdef$5b4a39281706f5e4d3c2b1a0f9e8d7c6b5a49382716a5b4c3d2e1f0a9b8c7d6e"

# Replace example hashes above with your own. To generate a hash in Python:
# import os, binascii, hashlib
# salt=os.urandom(12); iters=120000; pw=b"yourpassword"; dk=hashlib.pbkdf2_hmac("sha256", pw, salt, iters)
# print(f"pbkdf2${iters}${binascii.hexlify(salt).decode()}${binascii.hexlify(dk).decode()}")
