PLAYERDATA_CLIENT_ID = "yGhhyBnkZu_VA0Y5Qj0D-snMUQsHwXuq6NCt5S1TTWA"
PLAYERDATA_CLIENT_SECRET = "LFKNJ3ud-vdlhJbCTv1xnJwng-SacBz_WTicW1AYadc"
PLAYERDATA_TOKEN_URL = "https://app.playerdata.co.uk/api/oauth/token"
PLAYERDATA_GRAPHQL_URL = "https://app.playerdata.co.uk/api/graphql"
PLAYERDATA_ORG_ID = "539eca86-7a83-4d8d-af9d-b675ac5fa656"